### ISSUE TITLE
Removing the algorithms SpecCMI and NystromSpecCMI

### ISSUE THREAD

**Issue by zixuans** [msreis/featsel#2]
Hello!

Since I intend not to install the octave libraries, I would like to remove the algorithms SpecCMI and NystromSpecCMI before compiling the main program. However, as I followed the instructions in Section 4 to remove the SpecCMI algorithm, an error occured (see below):
![unnamed](https://user-images.githubusercontent.com/54684922/63970174-8439b380-ca71-11e9-8a0c-4a9a9feab3f6.png)
It seems that the rest of the files were compiled automatically, including the .cpp file of the NystromSpecCMI algorithm, so the octave libraries were needed, which were not installed.

And I tried to continue to remove the NystromSpecCMI algorithm, the following error occurred (see below):
![unnamed1](https://user-images.githubusercontent.com/54684922/63970453-2c4f7c80-ca72-11e9-8df7-00b4b0b6e7bc.png)
After executing these two commands (removing two algorithms), I also tried to type _make_ to compile the main program and the error showed above occurred.

Any idea why it happened and how to fix this problem? Thanks!

**Comment by gustavoem** [comment]
Thanks for submitting this issue! I'll be working on this asap, and hopefully we'll have an updated master branch until tomorrow. 

Also feel free to submit a PR if you have worked on this issue.

**Comment by gustavoem** [comment]
Current master branch does not have an Octave dependency anymore. Now, if you want to use SpecCMI or NystromSpecCMI, you should checkout to branch SpecCMI_NystromSpecCMI. See commits 0f2a907 and 6b668f7.
